apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
  namespace: default
spec:
  selector:
    app: simpletimeservice
  ports:
    - protocol: TCP
      port: 8000    
      targetPort: 8000  
  type: LoadBalancer
